# Rounded corners
corner-radius = 12
# Blur method
backend = "glx"
glx-no-stencil = true
# VSync to prevent tearing
vsync = true
# Opacity settings
opacity-rule = [
  "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
]
# Fading settings
fade = true
fade-delta = 4
fade-in-step = 0.03
fade-out-step = 0.03
# Shadow settings
shadow = true
shadow-opacity = 0.85
shadow-radius = 7
shadow-offset-x = -7
shadow-offset-y = -7
# AMD specific settings
detect-rounded-corners = true
detect-client-opacity = true
